version: "3"
services:
  flatpak:
    # cf. https://github.com/MaastrichtU-IDS/jupyterlab
    image: ghcr.io/maastrichtu-ids/jupyterlab:latest
    shm_size: '16g'
    volumes:
    - /data/flatpak:/home/jovyan/work
    environment:
      - JUPYTER_TOKEN=${PASSWORD}
      - VIRTUAL_HOST=flatpak.137.120.31.160.nip.io
      - LETSENCRYPT_HOST=flatpak.137.120.31.160.nip.io
      - VIRTUAL_PORT=8888
      # Configuring proxy manually is required to access internet in your container
      # because portainer devs are not competent enough to read the global docker config
    #  - HTTP_PROXY=http://proxy.unimaas.nl:3128
    #  - HTTPS_PROXY=http://proxy.unimaas.nl:3128
    #  - http_proxy=http://proxy.unimaas.nl:3128
    #  - https_proxy=http://proxy.unimaas.nl:3128
    #  - NO_PROXY=127.0.0.1,localhost,137.120.0.0/16
    # Containers deployed publicly need to be on the nginx network
    #networks:
    #  - nginx

# Also required to deploy containers publicly
#networks:
#  nginx:
#    name: nginx
#    external: true
